# Header
menu:
  Home: /
  Series: /series/
  Archives: /archives/
  About: /about/
  Projects: http://github.com/hscspring

# Content
excerpt_link: More
prev: Prev
next: Next
# reply: Reply
# share: Share
fancybox: true

# Sidebar
widgets:
- search
- music
- category
- recent_posts
- tag
- tagcloud


# Gitment
gitalk:
  id: 0eb512031083d6e7edfb
  secret: e830808995dd813ca26fed50573760963457da37

# Miscellaneous
# google_analytics:
# laibili_shortname: Yam
# rss: 
# google_site_verification: 
# baidu_site_verification: 
# favicon: 
music: http://qnimg.lovevivian.cn/miss.mp3